version: "3"
services:

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - '8000:8000'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - backend
    depends_on:
      - backend

  backend:
    build: backend
    container_name: backend
    command: npm run dev
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
